version: "3.9"
services:
  maglit:
    image: local/maglit:latest 
    build:
      context: .
      target: runner
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local